# Database Configuration
database:
  type: SQLITE # MYSQL or SQLITE
  mysql:
    host: "localhost"
    port: 3306
    name: "dynashop"
    table-prefix: "dynashop"
    username: "root"
    password: ""
  sqlite:
    file: "dynashop.db"

web-dashboard:
  enabled: false # Enable or disable the web interface
  port: 7070 # Port for the web interface
  history:
    # Nombre de jours de conservation des données d'historique
    retention-days: 30
    # Activer la purge automatique
    auto-purge: true

# Dynamic store configuration
actions:
  shaped: 1.25
  shapeless: 1.25
  furnace: 0.75

time-period: 15 # Duration of dynamic pricing period (in minutes)

default:
  price-min-multiply: 0.5 # Minimum multiplier for dynamic pricing
  price-max-multiply: 2.0 # Maximum multiplier for dynamic pricing

  price-min: 0.01 # Minimum price for dynamic pricing
  price-max: 1000.0 # Maximum price for dynamic pricing
  price-margin: 0.1 # Price margin for dynamic pricing

  buy-growth-rate: 1.00005 # Growth rate for dynamic pricing
  buy-decay-rate: 0.99998 # Decline rate for dynamic pricing
  sell-growth-rate: 1.00002 # Growth rate for dynamic pricing
  sell-decay-rate: 0.99995 # Decline rate for dynamic pricing

  price-increase: 1.0001 # Price increase for dynamic pricing
  price-decrease: 0.9999 # Price decrease for dynamic pricing

  stock-min: 0 # Minimum stock for dynamic pricing
  stock-max: 1000000 # Maximum stock for dynamic pricing
  stock-buy-modifier: 0.5 # Stock modifier for dynamic pricing
  stock-sell-modifier: 2.0 # Stock modifier for dynamic pricing

gui:
  refresh:
    default-items: 1000 # Default refresh time for the GUI in milliseconds (1000 ms = 1 second)
    critical-items: 300 # Refresh time for critical items in milliseconds (300 ms = 0.3 seconds)

# Cache settings
cache:
  mode: "full" # "full" or "realtime"
  # List of items that should always have up-to-date prices
  critical-items:
    # - "minerais:15"  # Example: gold is critical
    - "shop2:item3"  # Another example

  # Cache durations in seconds
  durations:
    price: 30
    display: 10
    recipe: 300
    stock: 20
    calculated: 60

# Configuration du système de taxes
tax:
  enabled: false
  # Destination mode for taxes: "player", "system" or "remove"
  # player: Sends the tax to a real player (must have played on the server)
  # system: Sends the tax to a system account (works even if it's not a real player)
  # remove: Simply removes the money from the economy (does not assign it to anyone)
  mode: "system"
  # Name of the player who will receive the taxes (if mode is "player" or "system"), if mode is "remove", this field is ignored
  receiver: "DynaShopBank"
  # Percentage of tax applied on purchases
  buy-rate: 5.0
  # Percentage of tax applied on sales
  sell-rate: 0.0
  # Log transactions in the console
  log-transactions: false

# Configuration du système d'inflation
inflation:
  enabled: false
  base-rate: 0.5 # Taux d'inflation de base (% par jour)
  transaction-multiplier: 0.001 # Facteur d'inflation basé sur les transactions (% par transaction)
  money-threshold: 1000000 # Seuil de masse monétaire
  money-rate: 0.1 # Taux d'inflation basé sur la masse monétaire (% par million au-delà du seuil)
  deflation-rate: 0.05 # Taux de déflation automatique (% par jour)
  update-interval: 24 # Intervalle de mise à jour de l'inflation (en heures)
  max-factor: 5.0 # Facteur d'inflation maximum
  
  # Taux d'inflation spécifiques par catégorie
  categories:
    food: 0.3 # Les aliments s'inflatent moins rapidement
    minerals: 0.8 # Les minéraux s'inflatent plus rapidement
    rare_items: 1.2 # Les objets rares s'inflatent encore plus rapidement
  
  # Taux d'inflation spécifiques par item (format: shopID:itemID)
  items:
    resource:diamond: 1.5 # Les diamants s'inflatent très rapidement
    farm:wheat: 0.2 # Le blé s'inflate très lentement

# Enchants value multipliers, for every level (if the item has this enchant, its value will be multiplied by the specified multiplier)
# Those values are cumulative if an item has multiples enchants ; they'll be applied after the value of the item stack was calculated ; they won't apply if the item value already has that enchantment
enchant_multipliers:
  AQUA_AFFINITY:
    1: 1.2
  BANE_OF_ARTHROPODS:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  BLAST_PROTECTION:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
  BREACH:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
  CHANNELING:
    1: 1.2
  CURSE_OF_BINDING:
    1: 1.0
  CURSE_OF_VANISHING:
    1: 1.0
  DENSITY:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  DEPTH_STRIDER:
    1: 1.2
    2: 1.5
    3: 1.9
  EFFICIENCY:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  FEATHER_FALLING:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
  FIRE_ASPECT:
    1: 1.2
    2: 1.5
  FIRE_PROTECTION:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
  FLAME:
    1: 1.2
  FORTUNE:
    1: 1.2
    2: 1.5
    3: 1.9
  FROST_WALKER:
    1: 1.2
    2: 1.5
  IMPALING:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  INFINITY:
    1: 1.2
  KNOCKBACK:
    1: 1.2
    2: 1.5
  LOOTING:
    1: 1.2
    2: 1.5
    3: 1.9
  LOYALTY:
    1: 1.2
    2: 1.5
    3: 1.9
  LUCK_OF_THE_SEA:
    1: 1.2
    2: 1.5
    3: 1.9
  LURE:
    1: 1.2
    2: 1.5
    3: 1.9
  MENDING:
    1: 1.2
  MULTISHOT:
    1: 1.2
  PIERCING:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
  POWER:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  PROJECTILE_PROTECTION:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
  PROTECTION:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
  PUNCH:
    1: 1.2
    2: 1.5
  QUICK_CHARGE:
    1: 1.2
    2: 1.5
    3: 1.9
  RESPIRATION:
    1: 1.2
    2: 1.5
    3: 1.9
  RIPTIDE:
    1: 1.2
    2: 1.5
    3: 1.9
  SHARPNESS:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  SILK_TOUCH:
    1: 1.2
  SMITE:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  SOUL_SPEED:
    1: 1.2
    2: 1.5
    3: 1.9
  SWEEPING_EDGE:
    1: 1.2
    2: 1.5
    3: 1.9
  SWIFT_SNEAK:
    1: 1.2
    2: 1.5
    3: 1.9
  THORNS:
    1: 1.2
    2: 1.5
    3: 1.9
  UNBREAKING:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  WIND_BURST:
    1: 1.2
    2: 1.5
    3: 1.9


# For translations/ > https://github.com/toxicity188/all-minecraft-language