# Database Configuration
database:
  type: SQLITE # MYSQL or SQLITE
  mysql:
    host: "localhost"
    port: 3306
    name: "dynashop"
    table-prefix: "dynashop"
    username: "root"
    password: ""
  sqlite:
    file: "dynashop.db"

# Dynamic store configuration
actions:
  shaped: 1.2
  shapeless: 1.1
  furnace: 1.5

time-period: 15 # Duration of dynamic pricing period (in minutes)

default:
  price-min-multiply: 0.5 # Minimum multiplier for dynamic pricing
  price-max-multiply: 2.0 # Maximum multiplier for dynamic pricing

  price-min: 0.01 # Minimum price for dynamic pricing
  price-max: 1000.0 # Maximum price for dynamic pricing
  price-margin: 0.1 # Price margin for dynamic pricing

  buy-growth-rate: 1.00005 # Growth rate for dynamic pricing
  buy-decay-rate: 0.99998 # Decline rate for dynamic pricing
  sell-growth-rate: 1.00002 # Growth rate for dynamic pricing
  sell-decay-rate: 0.99995 # Decline rate for dynamic pricing

  price-increase: 1.0001 # Price increase for dynamic pricing
  price-decrease: 0.9999 # Price decrease for dynamic pricing

  stock-min: 0 # Minimum stock for dynamic pricing
  stock-max: 1000000 # Maximum stock for dynamic pricing
  stock-buy-modifier: 0.5 # Stock modifier for dynamic pricing
  stock-sell-modifier: 2.0 # Stock modifier for dynamic pricing

# Paramètres de cache
cache:
  # Liste des items dont les prix doivent toujours être à jour
  critical-items:
    # - "minerais:15"  # Exemple: l'or est critique
    - "shop2:item3"  # Autre exemple
  
  # Durées de cache en secondes
  durations:
    price: 30
    display: 10
    recipe: 300
    stock: 20
    calculated: 60