# Database Configuration
database:
  type: SQLITE # MYSQL or SQLITE
  mysql:
    host: "localhost"
    port: 3306
    name: "dynashop"
    table-prefix: "dynashop"
    username: "root"
    password: ""
  sqlite:
    file: "dynashop.db"

# Dynamic store configuration
actions:
  shaped: 1.25
  shapeless: 1.25
  furnace: 0.75

time-period: 15 # Duration of dynamic pricing period (in minutes)

default:
  price-min-multiply: 0.5 # Minimum multiplier for dynamic pricing
  price-max-multiply: 2.0 # Maximum multiplier for dynamic pricing

  price-min: 0.01 # Minimum price for dynamic pricing
  price-max: 1000.0 # Maximum price for dynamic pricing
  price-margin: 0.1 # Price margin for dynamic pricing

  buy-growth-rate: 1.00005 # Growth rate for dynamic pricing
  buy-decay-rate: 0.99998 # Decline rate for dynamic pricing
  sell-growth-rate: 1.00002 # Growth rate for dynamic pricing
  sell-decay-rate: 0.99995 # Decline rate for dynamic pricing

  price-increase: 1.0001 # Price increase for dynamic pricing
  price-decrease: 0.9999 # Price decrease for dynamic pricing

  stock-min: 0 # Minimum stock for dynamic pricing
  stock-max: 1000000 # Maximum stock for dynamic pricing
  stock-buy-modifier: 0.5 # Stock modifier for dynamic pricing
  stock-sell-modifier: 2.0 # Stock modifier for dynamic pricing

gui:
  refresh:
    # default-items: 5 # Default refresh time for the GUI in seconds
    # critical-items: 1 # Refresh time for critical items in seconds
    default-items: 1000 # Default refresh time for the GUI in milliseconds (1000 ms = 1 second)
    critical-items: 300 # Refresh time for critical items in milliseconds (300 ms = 0.3 seconds)

# Paramètres de cache
cache:
  # Mode de cache : "full" pour un cache complet, "realtime" pour un cache en temps réel
  # Mode de cache "full" : les prix sont mis à jour périodiquement
  # Mode de cache "realtime" : les prix sont mis à jour en temps réel, mais peuvent être moins performants
  # Mode de cache "full" est recommandé pour les serveurs avec beaucoup de joueurs
  mode: "full" # "full" or "realtime"
  # Liste des items dont les prix doivent toujours être à jour
  critical-items:
    # - "minerais:15"  # Exemple: l'or est critique
    - "shop2:item3"  # Autre exemple
  
  # Durées de cache en secondes
  durations:
    price: 30
    display: 10
    recipe: 300
    stock: 20
    calculated: 60

# Enchants value multipliers, for every level (if the item has this enchant, its value will be multiplied by the specified multiplier)
# Those values are cumulative if an item has multiples enchants ; they'll be applied after the value of the item stack was calculated ; they won't apply if the item value already has that enchantment
enchant_multipliers:
  ARROW_DAMAGE:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  ARROW_FIRE:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  ARROW_INFINITE:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  ARROW_KNOCKBACK:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  DAMAGE_ALL:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  DAMAGE_ARTHROPODS:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  DAMAGE_UNDEAD:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  DEPTH_STRIDER:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  DIG_SPEED:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  DURABILITY:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  FIRE_ASPECT:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  KNOCKBACK:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  LOOT_BONUS_BLOCKS:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  LOOT_BONUS_MOBS:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  LUCK:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  LURE:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  OXYGEN:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  PROTECTION_ENVIRONMENTAL:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  PROTECTION_EXPLOSIONS:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  PROTECTION_FALL:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  PROTECTION_FIRE:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  PROTECTION_PROJECTILE:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  SILK_TOUCH:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  THORNS:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0
  WATER_WORKER:
    1: 1.2
    2: 1.5
    3: 1.9
    4: 2.5
    5: 3.0